// Generated by CoffeeScript 1.4.0
var $, CEP,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

$ = jQuery;

CEP = (function() {

  function CEP(el, opts) {
    this.el = el;
    this.success = __bind(this.success, this);

    this.send = __bind(this.send, this);

    this.enable = __bind(this.enable, this);

    this.disable = __bind(this.disable, this);

    this.clean = __bind(this.clean, this);

    this.cep = __bind(this.cep, this);

    this.changed = __bind(this.changed, this);

    this.valid = __bind(this.valid, this);

    this.search = __bind(this.search, this);

    this.$el = $(this.el);
    this.cache = {};
    this.lastCep = null;
    this.$el.on('keyup', this.search);
    this.$el.on('change', this.search);
    this.$el.on('blur', this.search);
    this.search();
  }

  CEP.prototype.search = function() {
    if (!(this.valid() && this.changed())) {
      return;
    }
    return this.send();
  };

  CEP.prototype.valid = function() {
    return this.cep().length === 8;
  };

  CEP.prototype.changed = function() {
    return this.cep() !== this.lastCep;
  };

  CEP.prototype.cep = function() {
    return this.el.value.replace(/\D/g, "");
  };

  CEP.prototype.clean = function() {
    console.log('clean');
    return $('#form-bairro,#form-cidade,#form-logradouro,#form-tipo_logradouro,#form-uf,#form-endereco').val('');
  };

  CEP.prototype.disable = function() {
    console.log('disable');
    return $('#form-cep,#form-bairro,#form-cidade,#form-logradouro,#form-tipo_logradouro,#form-uf,#form-endereco').attr('readonly', 'readonly');
  };

  CEP.prototype.enable = function() {
    console.log('enable');
    return $('#form-cep,#form-bairro,#form-cidade,#form-logradouro,#form-tipo_logradouro,#form-uf,#form-endereco').removeAttr('readonly');
  };

  CEP.prototype.send = function() {
    var cep, xhr;
    this.disable();
    cep = this.cep();
    if (this.cache[cep]) {
      this.enable();
      this.success(this.cache[cep]);
    } else {
      xhr = $.getJSON("http://cep.appspot.com/" + cep + ".json?callback=?");
      xhr.success(this.success);
      xhr.error(function() {
        return console.log('error');
      });
      xhr.complete(function() {
        return console.log('complete');
      });
    }
    return this.lastCep = cep;
  };

  CEP.prototype.success = function(json) {
    if (!json.ok) {
      return;
    }
    this.clean();
    $('#form-bairro').val(json.bairro);
    $('#form-cidade').val(json.cidade);
    $('#form-logradouro').val(json.logradouro);
    $('#form-tipo_logradouro').val(json.tipo_logradouro);
    $('#form-uf').val(json.uf);
    return $('#form-endereco').val("" + json.tipo_logradouro + " " + json.logradouro);
  };

  return CEP;

})();

$.fn.extend({
  cep: function(options) {
    var opts;
    opts = $.extend({}, self.default_options, options);
    return $(this).each(function(i, el) {
      return new CEP(el, opts);
    });
  }
});

$(function() {
  return $("input[data-cep]").cep();
});
