// Generated by CoffeeScript 1.4.0
var $;

$ = jQuery;

window.location.fullpaths = function() {
  var i, p, _results;
  p = this.pathname;
  _results = [];
  while ("" !== (p = p.substr(0, i))) {
    i = p.lastIndexOf('/');
    _results.push(this.protocol + '//' + this.host + p);
  }
  return _results;
};

$.qi = {
  version: "0.0.2",
  all: function(cfg) {
    if (cfg == null) {
      cfg = {};
    }
    this.print().back().active().timeago().bootstrap().submit().confirm();
    if (console && cfg.debug) {
      return console.log("qi.all executed!");
    }
  },
  print: function() {
    $("[data-print]").click(function() {
      window.print();
      return false;
    });
    return this;
  },
  back: function() {
    $("[data-back]").on('click', function() {
      window.history.back();
      return false;
    });
    return this;
  },
  active: function() {
    $("a[href^='/']").each(function() {
      var path, _i, _len, _ref, _results;
      _ref = window.location.fullpaths();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        path = _ref[_i];
        if (this.href === path) {
          _results.push($(this).closest('li').addClass('active'));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
    return this;
  },
  bootstrap: function() {
    if ($.fn.select2) {
      $('[data-select]').select2();
    }
    if ($.fn.tooltip) {
      $("[rel=tooltip],[data-tooltip]").tooltip();
    }
    if ($.fn.popover) {
      $("[data-popover]").popover();
    }
    $('.control-group').has('[required]').addClass('required');
    return this;
  },
  timeago: function() {
    if ($.fn.timeago) {
      $(".timeago").timeago();
    }
    return this;
  },
  submit: function() {
    $('form').submit(function() {
      var bt;
      if ($(this).data("confirm") && !confirm($(this).data("confirm"))) {
        return false;
      }
      bt = $(this).find('[type=submit]').attr('disabled', 'disabled');
      if (bt.val()) {
        return bt.val('enviando ...');
      } else {
        return bt.text('enviando ...');
      }
    });
    return this;
  },
  confirm: function() {
    $("a[data-confirm], button[data-confirm]").click(function() {
      return confirm($(this).data("confirm"));
    });
    return this;
  }
};
